### ISSUE TITLE
Using E-care for a client

### ISSUE THREAD

**Issue by ugintl** [Raayhan/E-Care#2]
Can I use e-care for a client?

**Comment by ugintl** [comment]
@Raayhan Your silence suggests that you have no problem :)

**Comment by Raayhan** [comment]
Hi there,
Sorry for the delay. You can use it but it would be great if you leave an
endorsement/recommendation on my Linkedin profile.
Thank you.
*Rayhan Ahmed Rakib*

**Comment by ugintl** [comment]
ok. What do you want me to write?

**Comment by Raayhan** [comment]
Anything positive would be appreciable :) 
https://www.linkedin.com/in/rayhan777/

**Comment by ugintl** [comment]
Are all of your projects free to use?

I saw your profile, but I do not see recommendation button.

**Comment by Raayhan** [comment]
Let me know before you use any of the projects I have to accept your request
on lnikedin after that you can give endorsements . no need to give
recommendations. Endorsements will be enough which is on the skills section
*Rayhan Ahmed Rakib*

**Comment by ugintl** [comment]
Done :)

**Comment by ugintl** [comment]
How to add more fields to the patient profile? I will try to do it my self. Just tell what files to edit.
